import { ApiProperty } from '@nestjs/swagger';

export class UpdateProdcutPayload {
  @ApiProperty({
    example: 'd47ef880-06cd-4fdc-aa63-1dad7b02b2ce',
    description: 'Product ID generated by the system',
  })
  id: string;
  @ApiProperty({
    example: 'iPhone 16',
    description: 'Name of the product',
  })
  productName?: string;
  @ApiProperty({
    example: 'Latest generation smartphone with advanced features',
    description: 'A short description of the product',
  })
  shortDesc?: string;
  @ApiProperty({
    example: 999.99,
    description: 'Price of a single unit of the product in USD',
  })
  itemPrice?: number;
  @ApiProperty({
    example: 100,
    description: 'Number of units available in stock',
  })
  availableStock?: number;
}
